name: build-latex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main-cu-prospectus.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main-cu-prospectus.pdf
